<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <AssemblyName>ThermoFisher.SampleOnionModule.AspNetCore</AssemblyName>
    <RootNamespace>ThermoFisher.SampleOnionModule.AspNetCore</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <WarningsAsErrors>nullable</WarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.6" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUi" Version="9.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SampleOnionModule.Contracts\SampleOnionModule.Contracts.csproj" />
    <ProjectReference Include="..\SampleOnionModule.Abstractions\SampleOnionModule.Abstractions.csproj" />
    <ProjectReference Include="..\SampleOnionModule\SampleOnionModule.csproj" />
  </ItemGroup>
</Project>
