<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ThermoFisher.SampleVerticalModule.Contracts</RootNamespace>
    <AssemblyName>ThermoFisher.SampleVerticalModule.Contracts</AssemblyName>
  </PropertyGroup>
</Project>
