<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Thermofisher.Opal.IpcDataAccessModule</RootNamespace>
    <AssemblyName>Thermofisher.Opal.IpcDataAccessModule</AssemblyName>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <GenerateAssemblyInfo>True</GenerateAssemblyInfo>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <GenerateAssemblyInfo>True</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.ComponentModel.DataAnnotations" />
    <Reference Include="System.Configuration" />
    <Reference Include="System.Runtime" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="ThermoFisher.Foundation.Acquisition, Version=3.1.322.0, Culture=neutral, PublicKeyToken=c5067b3d1110b13c, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\lib\ThermoFisher.Foundation.Acquisition.dll</HintPath>
    </Reference>
    <Reference Include="ThermoFisher.Foundation.Data, Version=3.1.322.0, Culture=neutral, PublicKeyToken=bff8ff310d6d23b1, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\lib\ThermoFisher.Foundation.Data.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Protobuf Include="..\protos\thermofisher.opal.rawdataaccess.proto" GrpcServices="Client">
      <Link>Protos\thermofisher.opal.rawdataaccess.proto</Link>
    </Protobuf>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Google.Protobuf">
      <Version>3.32.1</Version>
    </PackageReference>
    <PackageReference Include="Grpc.Core">
      <Version>2.46.6</Version>
    </PackageReference>
    <PackageReference Include="Grpc.Net.Client">
      <Version>2.71.0</Version>
    </PackageReference>
    <PackageReference Include="Grpc.Tools">
      <Version>2.72.0</Version>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Bcl.TimeProvider">
      <Version>9.0.9</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection">
      <Version>9.0.9</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging">
      <Version>9.0.9</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Console">
      <Version>9.0.9</Version>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Logging.Debug">
      <Version>9.0.9</Version>
    </PackageReference>
    <PackageReference Include="Polly">
      <Version>8.6.3</Version>
    </PackageReference>
    <PackageReference Include="System.ComponentModel.Annotations">
      <Version>5.0.0</Version>
    </PackageReference>
    <PackageReference Include="System.Configuration.ConfigurationManager">
      <Version>9.0.9</Version>
    </PackageReference>
    <PackageReference Include="System.Memory">
      <Version>4.6.3</Version>
    </PackageReference>
    <PackageReference Include="System.Threading.Tasks.Extensions">
      <Version>4.6.3</Version>
    </PackageReference>
    <PackageReference Include="System.ValueTuple">
      <Version>4.6.1</Version>
    </PackageReference>
    <PackageReference Include="Thermo.Library">
      <Version>5.1.0.13</Version>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>
</Project>
